[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-static",
]

[build]
target = "x86_64-unknown-linux-musl"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
OPENSSL_STATIC = "1" 
